# Lecture 1 - Tensors 

Everything we do in PyTorch when training neural networks is built on one fundamental data structure: tensors. Every step of the training process, loading data, running the forward pass, computing gradients, and updating weights relies on tensors. This means that all training and validation data must be converted into tensors before we start the training loop.

To understand how a neural network learns, and how to transform our input data into tensors, we need to understand the tensor format. A typical PyTorch tensor for image data (2D) follors the shape:

- (N, C, H, W)

Where

- N = Batch size 
- C = Number of channels 
- H = Height 
- W = Width

If you come from a GIS background, this may look familiar, similar to a multi‑dimensional array, such as a Sentinel‑2 image loaded with NumPy. The resemblance is intentional. However, PyTorch tensors have several unique capabilities, especially when it comes to GPU acceleration and automatic differentiation. These advantages will become clear by the end of this lecture.

In PyTorch, tensor objects are created using torch.Tensor. By the end of this lecture, you should be able to:

- create tensors

- manipulate tensors

- understand how tensors flow through a neural network

This is the foundation on which all of PyTorch is built.

## Part 1 - Create Tensors directly from data

If you have a NumPy array, and want to convert to a tensor, use the torch.tensor() function. 

In [19]:
import numpy as np
import torch

# This could be a one-channel image
np_data = np.array([[1, 2, 3],
                    [4, 5, 6]])

print("This is the NumPy array:")
print(np_data)
print()

# Convert NumPy array to PyTorch tensor
tens = torch.tensor(np_data)
print("This is the tensor:")
print(tens)
print()

print("\nThey look the similar, but are of different types:") 
type(np_data), type(tens)

This is the NumPy array:
[[1 2 3]
 [4 5 6]]

This is the tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


They look the similar, but are of different types:


(numpy.ndarray, torch.Tensor)

Note: NumPy prints arrays using spaces (matrix‑style), while PyTorch prints tensors using commas (Python‑list style). This is why they look slightly different even though the values are the same.

In [20]:
# Crucial difference is that we now can use GPU
if torch.cuda.is_available():
    tens_gpu = tens.to("cuda")
    print("Tensor moved to GPU:", tens_gpu.device)
else:
    print("No GPU available on this machine.")




Tensor moved to GPU: cuda:0


 ---
### NumPy vs PyTorch  
NumPy prints arrays using spaces (matrix‑style), while PyTorch prints tensors using commas (Python‑list style). This is why they look slightly different even though the values are the same.

Tensors can run on the GPU and support automatic differentiation. In the example above we convert a NumPy array into a tensor and check whether a GPU is available.